{{- if .Values.notifications.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bitwarden.fullname" . }}-notifications
  labels:
    app.kubernetes.io/name: {{ include "bitwarden.name" . }}
    helm.sh/chart: {{ include "bitwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: notifications
spec:
  replicas: {{ .Values.notifications.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bitwarden.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: notifications
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bitwarden.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: notifications
    spec:
      containers:
      - name: notifications
        image: "{{ .Values.notifications.image.repository }}:{{ default .Values.global.coreVersion .Values.notifications.image.tag }}"
        imagePullPolicy: {{ .Values.notifications.image.pullPolicy }}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
{{ include "bitwarden.global" . | indent 8 }}
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /alive
            port: http
        readinessProbe:
          httpGet:
            path: /alive
            port: http
        resources:
{{ toYaml .Values.notifications.resources | indent 10 }}
      tolerations:
{{ toYaml .Values.notifications.tolerations | indent 8 }}
      affinity:
{{ toYaml .Values.notifications.affinity | indent 8 }}
{{- end }}
