{{- if .Values.identity.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitwarden.fullname" . }}-identity
  labels:
    app.kubernetes.io/name: {{ include "bitwarden.name" . }}
    helm.sh/chart: {{ include "bitwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: identity
type: Opaque
data:
  identity.pfx: {{ .Values.identity.pfx | quote }}
  certificate-password: {{ .Values.identity.certificatePassword | b64enc | quote }}
{{- end }}
