{{- if .Values.web.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitwarden.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "bitwarden.name" . }}
    helm.sh/chart: {{ include "bitwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: web
data:
  app-id.json: |
    {
      "trustedFacets": [
      {
        "version": {
          "major": 1,
          "minor": 0
        },
        "ids": [
          "https://{{ .Values.global.host }}",
          "ios:bundle-id:com.8bit.bitwarden",
          "android:apk-key-hash:dUGFzUzf3lmHSLBDBIv+WaFyZMI"
        ]
      }
      ]
    }
  settings.js: |
    var bitwardenAppSettings = {
        iconsUri: "/icons",
        stripeKey: null,
        braintreeKey: null,
        selfHosted: true
    };
{{- end }}
