{{- if .Values.nginx.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bitwarden.fullname" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "bitwarden.name" . }}
    helm.sh/chart: {{ include "bitwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: nginx
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bitwarden.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bitwarden.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: nginx
      annotations:
        checksum/nginx-config: {{ include (print $.Template.BasePath "/nginx/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        livenessProbe:
          httpGet:
            path: /server_ping
            port: http
        readinessProbe:
          httpGet:
            path: /server_ping
            port: http
        resources:
{{ toYaml .Values.nginx.resources | indent 10 }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "bitwarden.fullname" . }}-nginx
      tolerations:
{{ toYaml .Values.nginx.tolerations | indent 8 }}
      affinity:
{{ toYaml .Values.nginx.affinity | indent 8 }}
{{- end }}
